services:
  fossiltracker:
    container_name: platelibrary
    image: davewalker5/fossiltracker:latest
    platform: linux/amd64
    restart: always
    ports:
      - "8095:8501"
    volumes:
      - /path/to/plate/library/database/folder:/var/opt/fossiltracker/
