services:
  fossiltracker:
    container_name: fossiltracker
    image: davewalker5/fossiltracker:latest
    platform: linux/amd64
    restart: always
    ports:
      - "8095:8501"
    volumes:
      - /path/to/fossil/tracker/database/folder:/var/opt/fossiltracker/
